### ISSUE TITLE
Defining Nornir Config File Ignored

### ISSUE THREAD

**Issue by bwks** [network-unit-testing-system/nuts#102]
Hey There,

Looks like when defining a Nornir config file when running tests the argument is ignored.

How I am running tests

```
pytest tests/switches/ --nornir-config=tests/nr-test-config.yml
```

NUTS Version: `nuts==3.3.0`

Directory Structure:
```
.
├── LICENSE
├── pyproject.toml
├── README.md
├── requirements.txt
├── requirements-user.txt
├── setup.py
└── tests
    ├── switches
    │   └── test-ping.yml
    ├── nr-test-config.yml
    ├── nr-test-defaults.yml
    ├── nr-test-groups.yml
    └── nr-test-hosts.yml
```

It seems that it fails unless I define a `nr-config.yaml`  in the project root directory

**Comment by ubaumann** [comment]
@bwks Thanks for opening this bug. It seems like we broke this somewhere along the way.
I need to check why this test is not working:
https://github.com/network-unit-testing-system/nuts/blob/d8e8d18af94a41e283b06538b3e8504e824ad8d6/tests/test_context.py#L189

**Comment by bwks** [comment]
Just wanted to say thank you @ubaumann :raised_hands:

**Comment by ubaumann** [comment]
You are welcome. At the moment the fix is in the main branch. Hope we release soon.

**Comment by ubaumann** [comment]
@bwks Just for your information, a new release containing the fix was published yesterday. I hope it works well for you now.
https://github.com/network-unit-testing-system/nuts/releases/tag/v3.4.0
